services:
  crm-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-crm-api:dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - dev-network

networks:
  dev-network: